---
- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  remote_user: ubuntu
  become: yes
  shell: |
    swapoff -a

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  remote_user: ubuntu
  become: yes
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'